version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./app-back
    container_name: fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./app-back:/app
    environment:
      # URL pour l'application FastAPI asynchrone
      - DATABASE_URL=postgresql+asyncpg://postgres:1234@db:5432/iot_db
      # URL pour les migrations Alembic (pilote synchrone standard obligatoire)
      - ALEMBIC_DATABASE_URL=postgresql://postgres:1234@db:5432/iot_db
    depends_on:
      - db

  frontend:
    build: ./app-front
    container_name: react_frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./app-front:/app
    stdin_open: true
    depends_on:
      - backend

volumes:
  postgres_data:
