"""add user table

Revision ID: 09a002ce8e8f
Revises: 5125f739c1e2
Create Date: 2026-04-11 00:09:45.563219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a002ce8e8f'
down_revision = '5125f739c1e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thresholds_id', table_name='thresholds')
    op.drop_table('thresholds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thresholds',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('minval', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('maxval', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], name='thresholds_node_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='thresholds_pkey')
    )
    op.create_index('ix_thresholds_id', 'thresholds', ['id'], unique=False)
    # ### end Alembic commands ###
